# Form implementation generated from reading ui file 'cupi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import ctypes

from PyQt6.QtGui import QIcon

myappid = 'omeritach.auto.prod.1.0' # arbitrary string
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
GWL_EXSTYLE=-20
WS_EX_APPWINDOW=0x00040000
WS_EX_TOOLWINDOW=0x00000080

class Ui_control_form(object):
    def setupUi(self, control_form):
        control_form.setObjectName("control_form")
        control_form.setFixedSize(250, 250)
        control_form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        app_icon = QtGui.QIcon()
        app_icon.addFile('gui/icons/16x16.ico', QtCore.QSize(16, 16))
        app_icon.addFile('gui/icons/24x24.ico', QtCore.QSize(24, 24))
        app_icon.addFile('gui/icons/32x32.ico', QtCore.QSize(32, 32))
        app_icon.addFile('gui/icons/48x48.ico', QtCore.QSize(48, 48))
        app_icon.addFile('gui/icons/256x256.ico', QtCore.QSize(256, 256))
        control_form.setWindowIcon(QIcon('gui/icons/256x256.ico'))
        self.tabWidget = QtWidgets.QTabWidget(parent=control_form)
        self.tabWidget.setGeometry(QtCore.QRect(-1, 0, 252, 252))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setGeometry(QtCore.QRect(140, 10, 91, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.label_time = QtWidgets.QLabel(parent=self.tab)
        self.label_time.setGeometry(QtCore.QRect(16, 20, 40, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        self.label_time.setFont(font)
        self.label_time.setWordWrap(False)
        self.label_time.setObjectName("label_time")
        self.time_line = QtWidgets.QLineEdit(parent=self.tab)
        self.time_line.setGeometry(QtCore.QRect(56, 20, 61, 20))
        self.time_line.setObjectName("time_line")
        self.time_line.setText("5")
        self.comboBox = QtWidgets.QComboBox(parent=self.tab)
        self.comboBox.setGeometry(QtCore.QRect(140, 60, 91, 22))
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(88, 190, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.tab)
        self.checkBox.setGeometry(QtCore.QRect(16, 60, 111, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_created = QtWidgets.QLabel(parent=self.tab_2)
        self.label_created.setGeometry(QtCore.QRect(0, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.label_created.setFont(font)
        self.label_created.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_created.setObjectName("label_created")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.tab_2)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.textBrowser.setGeometry(QtCore.QRect(0, 30, 245, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.tab_3)
        self.textBrowser_2.setOpenExternalLinks(True)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 245, 220))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(control_form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(control_form)

    def retranslateUi(self, control_form):
        _translate = QtCore.QCoreApplication.translate
        control_form.setWindowTitle(_translate("control_form", "Anti Idle"))
        control_form.setWindowIcon(QIcon('gui/icons/256x256.ico'))
        self.pushButton.setText(_translate("control_form", "Start"))
        self.label_time.setText(_translate("control_form", "Time"))
        self.comboBox.setCurrentText(_translate("control_form", "Bright Theme"))
        self.comboBox.setItemText(0, _translate("control_form", "Bright Theme"))
        self.comboBox.setItemText(1, _translate("control_form", "Black Theme"))
        self.pushButton_2.setText(_translate("control_form", "Exit"))
        self.checkBox.setText(_translate("control_form", "Mouse Movment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("control_form", "Anti Idle Bot"))
        self.label_created.setText(_translate("control_form", "Instructions:"))
        self.textBrowser.setHtml(_translate("control_form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "hr { height: 1px; border-width: 0; }\n"
                                            "li.unchecked::marker { content: \"\\2610\"; }\n"
                                            "li.checked::marker { content: \"\\2612\"; }\n"
                                            "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. The &quot;Time&quot; box set the minimum idle time till the bot start.</p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Press once on &quot;Start&quot; and the Bot will start to run in the background.</p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. To temporarily stop the bot, move the mouse to the top left of the screen.</p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. To continue it move the moush to the left bottom part of the screen.</p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5. To completely stop the bot, press on the &quot;Start&quot; button again.</p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("control_form", "About"))
        self.textBrowser_2.setHtml(_translate("control_form",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "hr { height: 1px; border-width: 0; }\n"
                                              "li.unchecked::marker { content: \"\\2610\"; }\n"
                                              "li.checked::marker { content: \"\\2612\"; }\n"
                                              "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Linkedin: <a href=\"https://www.linkedin.com/in/omer-itach/\"><span style=\" text-decoration: underline; color:#0000ff;\">Linkedin</span></a></p>\n"
                                              "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">GitHub: <a href=\"https://github.com/omerapp99\"><span style=\" text-decoration: underline; color:#0000ff;\">GitHub</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("control_form", "Links"))

if __name__ == "__main__":
    Ui_control_form()
